[package]
name = "dory"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", default-features = false, features = ["derive"] }

[workspace.lints.clippy]
pedantic = "warn"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]
